### ISSUE TITLE
mypy integration

### ISSUE THREAD

**Issue by iddan** [MagicStack/immutables#12]
Collections should implement [mypy Mapping generic](https://mypy.readthedocs.io/en/stable/generics.html#defining-sub-classes-of-generic-classes) to be properly typed

**Comment by antonagestam** [comment]
I'd be happy to get the ball rolling if PR's will be considered for this :)

**Comment by iddan** [comment]
You just made my day 😄

**Comment by antonagestam** [comment]
It turned out that this what a bit more complicated than I originally thought. For types such as `Map[str, int]` to not break at runtime the `Map` class needs to be subscribable. You normally achieve that by making it inherit from `typing.Mapping` (or `typing.Generic`). But since `Map` is implemented as a C extension this doesn't seem that straight forward. It might be simple to do this in the C implementation though, I'll try and dig further when I get the time.

**Comment by antonagestam** [comment]
Got some tips in the typing gitter channel: https://gitter.im/python/typing?at=5d25bd59cdb70805c96e239f
